name: catalyst_dapp_connector
description: A package that supports CIP-30 and CIP-62 functionality.
version: 1.0.0
repository: https://github.com/input-output-hk/catalyst-flutter
issue_tracker: https://github.com/input-output-hk/catalyst-flutter/issues
homepage: https://github.com/input-output-hk/catalyst-flutter
documentation: https://github.com/input-output-hk/catalyst-flutter
environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_js: ^0.6.0
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
